const pressQuotes = [
    { id: 1, presenter: 'Utah Festival Opera', production: 'Le nozze di Figaro', role: 'Countess Almaviva', content: `I must kowtow to Bridgette Gan who plays the Countess Almaviva, the long suffering wife of the womanizing Count. Gan is exquisite as the Countess. Her first aria that opens Act II, “Porgi, amor, qualche ristoro,” (or, “Grant, love, some comfort“) is beautifully sung and staged by director Suzan Hanson. The Countess stands, her back to the audience, framed in an archway, her thoughts assuredly on her husband. Gan sings this heartfelt aria wrenchingly, with artistry and amazing control. Hanson and Gan trust the music to carry the moment, keeping the action simple. Gan's Act III aria, “Dove sono i bei momenti” is just as exquisite with Gan adding embellishments and nuances I've never heard before, which deepens its lush beauty.`, author: 'Elizabeth Hansen', publication: 'Utah Theatre Bloggers'  },
    { id: 2, presenter: 'Utah Festival Opera', production: 'Le nozse di Figaro', role: 'Countess Almaviva', content: `As Act II opened, Countess Almaviva (Bridgette Gan) provided a production highlight with her lamentation over her husband's infidelity. It was heartfelt and pointed, and labeled Gan as the one to listen to.`, author: 'Jay Wamsley', publication: 'Deseret news' },
    { id: 3, presenter: 'Utah Festival Opera', production: 'Le nozze di Figaro', role: 'Countess Almaviva', content: `Director Suzan Hanson gets marvelous performances from her entire cast, especially Rose-Antoinette Bellino and Bridgette Gan. Both women are impressive vocalists and their superb acting is just frosting on the cake.  As Rosina, the Countess Almaviva, Ms. Gan nicely balances what could have been contradictory roles as a tragically estranged spouse and a playfully amused object of a juvenile suitor's affections.`, author: 'Charlie Schill', publication: 'Utah Public Radio' },
    { id: 4, presenter: 'Utah Festival Opera', production: 'Masterclass', role: 'Sharon', content: `Bridgette Gan, as Sharon, the second Soprano is perfect in the role, and when she and Hanson interact, Hanson's innate vulnerability and love of opera works.`, author: 'Elizabeth Hansen', publication: 'Utah Theatre Bloggers' },
    { id: 5, presenter: 'Utah Festival Opera', production: 'Masterclass', role: 'Sharon', content: `Supporting cast members add lust and depth to the drama...Bridgette Gan beautifully performs an aria from “Macbeth”`, author: 'Charlie Schill', publication: 'The Hearald Journal' },
    { id: 6, presenter: 'St. Petersburg Opera', production: `L'elisir d'amore`, role: 'Adina', content: `But the real draw is the promising Bridgette Gan as Adina, who made a strong impression in her St. Petersburg Opera debut. From her opening aria, Of the Cruel Isolda, Gan captures the ear and eye with power and precision. She also made use of other bel canto staples, such as the gradual crescendo and decrescendo, a portamento or glide between notes, and the artful gesture as part of a song's delivery. It was hard to watch her performance and imagine anyone else playing Adina.`, author: 'Andrew Meacham', publication: 'Tampa Bay Times' },
    { id: 7, presenter: 'Opera Orlando', production: 'Don Pasquale', role: 'Norina', content: `Gan, who sports a clear, ringing soprano, has a saucy sparkle in her eyes--when Pasquale calls her a minx, you believe it.`, author: 'Matthew J. Palm', publication: 'Orlando Sentinel' },
    { id: 8, presenter: 'Opera Orlando', production: 'The Impresario', role: 'Bethany Squeals', content: `A tarted-up Bridgette Gan particularly sparkles, vocally and comically.`, author: 'Matthew J. Palm', publication: 'Orlando Sentinel' },
    { id: 9, presenter: 'Palm Beach Opera', production: 'Opera on the Waterfront', role: 'Zerbinetta', content: `Next came the amazing Bridgette Gan, a fellow last year, now an opera star. Her soprano could break glass: the range is sensational and her pitch, perfection, as she sang Zerbinetta's Rondo from Strauss's Ariadne Auf Naxos. Impresarios will be happy to hire her. She'll fill seats with a command of vocal pyrotechnics like hers.`, author: 'Rex Hearn', publication: 'Palm Beach Arts Paper' }
    { id: 10, presenter: 'Palm Beach Opera', production: 'The Daughter of the Regiment', role: 'Marie', content: `Singing the role of Marie Saturday night was Palm Beach Opera Young Artist, Bridgette Gan (soprano). The role of Marie is a blend of coloratura and comic gags. Gan has lovely crystal clear high notes and a comic presence that brings to mind a slightly more refined Elly May Clampett.`, author: '' }
]